import{a as v,S as E,i}from"./assets/vendor-DKtxmrwh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const $="https://pixabay.com/api/",R="50426597-51e17373704e5765d60c36e2e",B=15;async function p(n,t=1){const r={key:R,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:B};try{return(await v.get($,{params:r})).data}catch(s){throw new Error(`Failed to fetch images: ${s.message}`)}}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),O=new E(".gallery a",{captionsData:"alt",captionDelay:250});function g(n){const t=n.map(({webformatURL:r,largeImageURL:s,tags:e,likes:o,views:c,comments:S,downloads:q})=>`
        <li class="gallery-item">
          <a href="${s}">
            <img src="${r}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${o}</p>
            <p><b>Views:</b> ${c}</p>
            <p><b>Comments:</b> ${S}</p>
            <p><b>Downloads:</b> ${q}</p>
          </div>
        </li>`).join("");m.insertAdjacentHTML("beforeend",t),O.refresh()}function M(){m.innerHTML=""}function y(){f.classList.remove("hidden")}function b(){f.classList.add("hidden")}function L(){h.classList.remove("hidden")}function d(){h.classList.add("hidden")}const w=document.querySelector(".form"),A=w.querySelector('input[name="search-text"]'),H=document.querySelector(".load-more-btn");let u="",a=1,l=0;const P=15;w.addEventListener("submit",async n=>{n.preventDefault();const t=A.value.trim();if(!t){i.warning({message:"Please enter a search query.",position:"topRight"});return}u=t,a=1,l=0,M(),d(),y();try{const r=await p(u,a);if(r.hits.length===0){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),d();return}l=r.totalHits,g(r.hits),i.success({message:`Hooray! We found ${l} images.`,position:"topRight"}),a*P<l?L():d()}catch{i.error({message:"Oops! Something went wrong. Please try again later.",position:"topRight"})}finally{b()}});H.addEventListener("click",async()=>{a+=1,y(),d();try{const n=await p(u,a);g(n.hits);const t=document.querySelector(".gallery");if(t.firstElementChild){const{height:r}=t.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}a*P>=l?(d(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch{i.error({message:"Oops! Something went wrong. Please try again later.",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
